### ISSUE TITLE
Implement 'Login with Github' feature

### ISSUE THREAD

**Issue by jkmdev** [deepanjali19/GitHub-Dashboard#13]
We need a way for users for login to the app with their Github account using the API's means of authenticating users.

[Documentation](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/)
[Example Implementation](https://developer.github.com/v3/guides/basics-of-authentication/)

**Comment by iblacker** [comment]
I can work on this

**Comment by jkmdev** [comment]
Alright, thanks @iblacker. Note that you need to [register an application](https://github.com/settings/applications/new) to implement this feature. I was looking into it to see if there was anything I needed to do on my end, but I think you could implement this on your own by entering `http://localhost:3000` for the Homepage URL and Authorization callback URL. If you run into any issues with this let me know.
