### ISSUE TITLE
Create welcome page

### ISSUE THREAD

**Issue by jkmdev** [deepanjali19/GitHub-Dashboard#25]
Create a welcome page that's something like: https://i.imgur.com/7xaPWcw.png
You can make it look like the one in the image or use your own design. Should have an image, text describing the app, and add the already implemented 'login with github' button to the main page.

When the user is already logged in/authorized to see the app they shouldn't see the welcome page. They should route directly to the [home](https://i.imgur.com/ahDfgZv.png) page.

**Comment by deepanjali19** [comment]
Hey I will work on this issue 👍
