### ISSUE TITLE
Create homepage

### ISSUE THREAD

**Issue by jagmeetb** [deepanjali19/GitHub-Dashboard#4]
- create home page with "login with github" button
- decide on languages/frameworks used

____

after that we can start working with github API to grab data

**Comment by ksandhu16** [comment]
I can work on this issue using technologies such as: HTML,CSS, and JavaScript.

**Comment by jkmdev** [comment]
Would we want to use some sort of framework as well? Perhaps React?

**Comment by ksandhu16** [comment]
React is perfect!

**Comment by jagmeetb** [comment]
We can use [Create React App](https://facebook.github.io/create-react-app/) to get started. It creates a simple React app with 1 command line command.

After that we can start designing the site.

**Comment by ksandhu16** [comment]
Sounds good, I will start it.

**Comment by deepanjali19** [comment]
Hey @ksandhu16 any idea when you can upload the homepage? I wanted to contribute to this repo, but I'm just waiting for your PR so I can start working.

**Comment by jagmeetb** [comment]
I can do this today/tomorrow if he hasn't done it yet

**Comment by deepanjali19** [comment]
Thanks @jagmeetb ! Let me know if you need any help.

**Comment by ksandhu16** [comment]
Sorry to reply late, I am still working on it. I just have small issue which I will resolve be tomorrow night.

**Comment by deepanjali19** [comment]
@ksandhu16 we can discuss those issue on Slack if you need any help. Or you can add what you got and we all can create new issues from it.

**Comment by ksandhu16** [comment]
They are very small issues, thank you for asking but I dont need help. I will upload the homepage by tomorrow night.

**Comment by deepanjali19** [comment]
@ksandhu16 sounds great !
